language: python
python:
- '3.4'
branches:
  except:
    - master
    - ci
env:
  matrix:
    - FORMAT=hst TF=M1
    - FORMAT=hst TF=M2
    - FORMAT=hst TF=M3
    - FORMAT=hst TF=M4
    - FORMAT=hst TF=M5
    - FORMAT=hst TF=M6
    - FORMAT=hst TF=M10
    - FORMAT=hst TF=M12
    - FORMAT=hst TF=M15
    - FORMAT=hst TF=M20
    - FORMAT=hst TF=M30
    - FORMAT=hst TF=H1
    - FORMAT=hst TF=H2
    - FORMAT=hst TF=H3
    - FORMAT=hst TF=H4
    - FORMAT=hst TF=H6
    - FORMAT=hst TF=H8
    - FORMAT=hst TF=H12
    - FORMAT=hst TF=D1
    - FORMAT=hst TF=W1
    - FORMAT=hst TF=MN1
    - FORMAT=fxt TF=M1
    - FORMAT=fxt TF=M5
    - FORMAT=fxt TF=M15
    - FORMAT=fxt TF=M30
    - FORMAT=fxt TF=H1
    - FORMAT=fxt TF=H4
    - FORMAT=fxt TF=D1
    - FORMAT=fxt TF=W1
    - FORMAT=fxt TF=MN1
addons:
  apt:
    packages:
    - realpath
    - pv
notifications:
  email: false
before_install:
- set -e
install: 
before_script:
- curl -o Makefile https://raw.githubusercontent.com/FX-Data/FX-Data-Test/master/Makefile
script:
- make $FORMAT
after_success: 
after_failure:
- sudo apt-get -qy install tree && tree -d -L 6
- env
after_script:
- pwd
deploy:
  provider: releases
  api_key:
    secure: "WRW49ilbKF3tRpg/LBEQ7Uc0hzumz2FmHmr4xaneaVls32aEsxF9JLYMajEoI2oRdtCy1OfLQeu+8l4pEH9VD+MTUgfvVECL9c8Pc5eQQTToE5EAgGlqBDS49k7azrkyRZ/jtz4kLQA/PjkRQaKMTvukCVL5y4tL1iFuw/fhTz0YoRoSd178GRcOyf6BEW3U/65IygaXWsdgeFlmizeG7ggSFX79cv8iuYhj/90oOcRxt61EEP3NIFrDPgqBm4+iIT3DAQay/HBXJCzrGQwkwJ3WQbsupNg3AYk350Gk/4kop5ydmt4n9ka7VkgqYp15i1ITZCXB+ZTASeYdRcml11iUWZVN3AoS1sIWO5lVNhED/8hWEPwvET9XZuXXhxerlV3O3HVpycb1bf0p8m1iizCMtQdzjxQ537+el+O4jteu+AuCEaNbe/lIbqxauCe9JVrzMMX/JrP798cO2CDwgvZq/pJ0pswOoSAwqK/514RuQXOblKWzbidHzSfuB/MFtBkxj+Y1oHFFIX3dDzFPPx5Z9k8HQZHO+M3EKQiFsE271XN/3sgUnu4CgDzzKJV05UNLaynYnRPj5JaFu5NwLol/bwc5ywqyvBGnoChJIJQYHFtHsc0s7JMzshRsV9qU2cB1WqNPae1ioZqnlvm+6uT7CA+Q4GyFOmQz2WoFwjI="
  file:
    - "*.hst.gz"
    - "*.fxt.gz"
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    repo: FX-Data/FX-Data-GBPJPY-DS
    tags: true
after_deploy:
- make clean
